services:
  dev:
    image: node:22-bookworm
    working_dir: /workspace
    env_file: .env
    tty: true
    command: sleep infinity
    ports:
      - "4321:4321"
      - "4322:4322"
    volumes:
      - .:/workspace

