services:
  dev:
    image: node:22-bookworm
    working_dir: /workspace
    env_file: .env
    tty: true
    command: sleep infinity
    ports:
      - "3333:3333"
      - "4321:4321"
      - "4173:4173"
      - "5173:5173"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/workspace

